[package]
name = "path_finding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
wasm-bindgen-futures = "0.4"
log = "0.4.20"
